#!/usr/bin/env python3
import argparse, sys
from libdrep import Package

def main():
    
    parser = argparse.ArgumentParser(description='Debian Repository Package Manager',
             epilog='Easily manage debian packages in a drep repository. ' 
                    'Copyright SAIT (C) Radlab, Applied Research 2013')

    parser.add_argument('command', nargs=1,
                        help='add, del, move, copy, info')
    parser.add_argument('package', nargs=2,
                        help='Name and Version, Ex: "testpackage 0.1"')
    
    parser.add_argument('--component',  action='append', nargs='*',
                        help='Specify a component')
    parser.add_argument('--repo', action='append', nargs='*',
                        help='Specify a repository')
    parser.add_argument('--arch', 
                        help='Specify an architecture')
    
    parser.add_argument('--sign', action='store_true',
                        help='Signs debian packages with a gpg key provided' 
                        ' a key has been created')
    
    parser.add_argument('--refresh', 
                        help='Remove and re-create the package, '
                        'removing all older versions if found')
    parser.add_argument('--conf', 
                        help='Use a specific configuration file'
                        ' (defaults to /etc/drep/drep.conf)')
    
    parser.add_argument('--noninteractive', action='store_true',
                        help='Any command that is run should do so '
                        'without prompting user. Use defaults and environmental'
                        ' vars whenever possible or fail.')
    
    parseargs = parser.parse_args(sys.argv[1:])
    print(parseargs)


if __name__ == "__main__":
    main()
    sys.exit(0)