#!/usr/bin/env python3

"""
Python-based debian repository management system

:Progress:
    o Create action implemented that seems to create the directory structure and
      required files.
      
    o Directory parameter is saved into the configuration file so it can 
      be used to automatically point to the repo provided the config file
      is specified and proper. By default, /etc/apt-repo.d/ is used and
      provided sudo or root privileges are used, no cli args have to be
      specified to continue with any repo action.

:Description:
    This software project has no affiliation with Debian's Official apt system.
    
    Manages and automates a repository with emphasis on the greatest ease of
    automation and control.
    
    This program aims to do as much as possible for the user and automate all
    the small details so the user doesn't have to worry about them. Automate
    gpg and hashes, update them whenever an update is called for, create
    files for all possible scenarios whenever possible -- always create 
    options for source, even if it isn't used.
    
    :create:
        By default, this creates a repository in the current directory with 
        defaults for a stable main repository. 

:Copyright:
    (C) 2015 PeonDevelopments
    (C) 2015 Angry Coders Inc.
"""

import argparse, sys, os, platform
import datetime
import platform
import logging
import socket
import hashlib
import shutil
import json
import shelve
import configparser
from aptrepo.lib.scanpackages import Packages_gz
from aptrepo.lib.arch import arch, get_arch, arch_dir
from aptrepo.lib.security import md5sum_file, gen_gpg_key

ARGS_TO_CONF = {"architecture": lambda x: ', '.join(x),
                "restrictions": lambda x: ', '.join(x),
                "https": lambda x: "true" if x else "false"}
CONF_TO_ARGS = {"architecture": lambda x: [y.strip() for y in x.split(',')],
                "restrictions": lambda x: [y.strip() for y in x.split(',')],
                "https": lambda x: True if x.lower() == "true" or x.lower() == "yes" else False}

def load_config_file(path, platform):
    path = os.path.join(path, platform)
    if not os.path.exists(path):
        raise Exception("Configuration File not found: {}".format(path))
    
    cp = configparser.ConfigParser()
    cp.optionxform = str
    cp.read(path)
    db = {}
    
    for section in cp.sections():
        for key in cp[section]:
            if key in CONF_TO_ARGS:
                db[key] = CONF_TO_ARGS[key](cp[section][key])
                
            else:
                db[key] = cp[section][key]
            
    return db

def write_config_file(path, platform, db):
    cp = configparser.ConfigParser()
    cp[platform] = db
    for arg in ARGS_TO_CONF.keys():
        if arg in db:
            cp[platform][arg] = ARGS_TO_CONF[arg](db[arg])
        
    print("Writing default config template to {}".format(configpath))
    with open(configpath, 'w') as f:
        cp.write(f)
        
        
ACTIONS = ["create", "delete", "update", "info", "add", "remove", "export", "gpg", "haspkg", "help", None]

if __name__ == "__main__":
    '''
    TODO:
        Write Release files with md5sum on Packages{.gz} and Sources{.gz} if applicable
        
    '''
    def format_deb_line(ip,  platforms, restrictions, https=False):
        return "deb http{}://{}/ {} {}".format("s" if https else "", ip,
                                                 ' '.join(platforms), ' '.join(restrictions))
    # --> Start Command Line Argument parsing
    parser = argparse.ArgumentParser(description="Debian Repository Management Tool",
                                     usage="%(prog)s [repo-platform] [action] (cli options)")
    parser.add_argument('action', nargs='*',
                       help="Run 'apt-repo help' to list all the actions")
    parser.add_argument('--desc', nargs='?', 
                        help="Set a repository description")
    parser.add_argument('--configdir', '-c', nargs='?', default=os.path.join(os.sep, 'etc', 'apt-repo.d'),
                        help="Specify directory where repo configuration files are kept")
    parser.add_argument('--directory', '-d', nargs='?', default=os.path.abspath(os.getcwd()),
                        help="Sets the top level directory for filesystem repositories")
    parser.add_argument('--name', '-n', nargs='?', 
                        help="Sets the account name of the repository")
    parser.add_argument('--email', '-e', nargs='?', 
                        help="Sets the account email address")
    parser.add_argument('--ip', '-i', nargs=1, help="Overrides the auto ip discovering feature")
    parser.add_argument('--gpg', '-g', nargs=1, #"./apt-repo.public.key",
                        help="Exports (and optionally creates) the gpg key to target path and filename") # TODO: Confirm use case of this option
    parser.add_argument('--architecture', '-a', nargs="*", 
                        help="Architectures to create repository with; defaults to current arch and source")
    parser.add_argument('--toplevel', '-t', nargs="?", help="name of top level directory; defaults to 'debian'")
    parser.add_argument('--restrictions', '-r', nargs="*", 
                         help="Package Freedom Restrictions (main, contrib, non-free), defaults to 'main'")
    parser.add_argument('--https', '-s', action="store_true", default=None, # FIXME: This should also take the server key as param to deploy
                        help="Sets the apt address to https instead of http")
    args = parser.parse_args()
    # <-- End Command Line Argument parsing
    platform = args.action[0] if len(args.action) > 0 else None
    action = args.action[1] if len(args.action) > 1 else None
    if len(args.action) < 2:
        raise Exception("Not enough Arguments: apt-repo [platform] [action]")
    
    if action is None:
        raise Exception("Action is required: {}".format(', '.join(
            [str(a) for a in filter(lambda x: not x is None, ACTIONS)])))

    configpath = os.path.join(args.configdir, platform)
    opts = dict(desc="<Description Goes Here>",
                directory=args.directory,
                name="",
                email="no-reply@localhost.com",
                architecture=[arch()],
                toplevel="debian" if args.toplevel is None else args.toplevel,
                restrictions=['main'],
                https=False)
    
    # Update from defaults
    for k, v in vars(args).items():
        if k in ["action"]:
            continue
        
        if not v is None:
            opts[k] = v
    
    # Path to the first portion of the repository:
    path = os.path.join(opts.get('directory'), opts.get('toplevel'), 'dists')
    
    # Start checking and performing actions
    if action == "create":
        # Create the configuration directory
        if not os.path.exists(args.configdir):
            try:
                print("Creating configuration directory")
                os.makedirs(args.configdir, exist_ok=True)
                
            except Exception as E:
                print(E)
                sys.exit(1)    
                
            
        # Create the configuration file
        if not os.path.exists(configpath):
            write_config_file(args.configdir, platform, opts)
        
        # Start Create action process
        umask = os.umask(0o022)
        if not os.path.exists(path):
            os.makedirs(path, exist_ok=True)
            
        # Create pool directories
        for x in opts.get('restrictions'):
            os.makedirs(os.path.join(opts.get('directory'), opts.get('toplevel'), 'pool', x),
                        exist_ok=True)
            
        # Before the Release file is created, we need the following files to be created and filled out. TODO
        # RESEARCH THIS NOW
        relfiles = ["Packages", "Packages.gz", "Sources", "Sources.gz"]
        with open(os.path.join(path, 'Release'), 'w') as f:
            f.write("Origin: {}\n".format(opts.get('name')))
            f.write("Label: {}\n".format(opts.get('name')))
            f.write("Suite: {}\n".format('wheezy'))
            f.write("Codename: {}\n".format('wheezy')) # FIXME
            f.write("Date: {}\n".format(datetime.datetime.strftime(datetime.datetime.now(), "%a, %d %b %Y %H:%M:%S %Z")))
            f.write("Architectures: {}\n".format(' '.join([get_arch(a) for a in opts.get('architecture')])))
            f.write("Components: {}\n".format(' '.join(opts.get('restrictions'))))
            f.write("Description: {}\n".format(opts.get('desc')))
            f.write("MD5Sum:\n")
            for x in relfiles:
                if os.path.exists(os.path.join(path, x)):
                    f.write(" {}\n".format(md5sum_file(path, x)))
                    
        # IMPORTANT! GNU GPG requires some work going on in order to generate entropy
        # This is a stop-gap for an important step.
        #        with open(os.path.join(path, 'Release.gpg'), 'w') as f:
        #            f.write("")

        for y in opts.get('restrictions'):
            for z in opts.get('architecture'):
                z = arch_dir(get_arch(z))
                os.makedirs(os.path.join(path, platform, y, z),
                            exist_ok=True)

                with open(os.path.join(path, platform, y, z, "Release"), 'w') as f:
                    f.write("Archive: {}\n".format(platform))
                    f.write("Origin: {}\n".format(opts.get('name')))
                    f.write("Label: {}\n".format(opts.get('name')))
                    f.write("Component: {}\n".format(y))
                    f.write("Architecture: {}\n".format(z))
                    #f.write("Version: 0.1\n")
                        
    
    elif action == "update":
        # update config file then pass updates onto the repository
        if os.path.exists(os.path.join(args.configdir, platform)):
            db = load_config_file(args.configdir, platform)
            for k, v in vars(args).items():
                if k in ["action", "configdir"]:
                    continue
                
                if not v is None:
                    db[k] = v
                    
            write_config_file(path, platform, db)
            
        else:
            raise Exception("Configuration File not Found")

    """
    elif action == "delete":
        umask = os.umask(0o022)
        
        toremove = os.path.join(opts.get('directory'), opts.get('toplevel'))
        print("\tRemoving {}".format(toremove))
        if os.path.exists(toremove):
            shutil.rmtree(toremove)
            
        else:
            sys.stderr.write("Error: Failed to remove non-existant directory: {}\n".format(
                toremove))
            sys.exit(2)
        
    elif action == "info":
        '''
        INFO:
            - List all the packages that exist in the components specified in the arguments
            - List each component of the repository that exists
            - List total stats of each repo section
            - List the ip address of the repo, list the deb line for the sources file
        '''
        
        if os.path.exists(path):
            # TODO: valid={check if repo structure works}
            pkgs = {}
            def repo_dict(repository, pkgs):
                return {"packagecount": len(pkgs[repository]),
                        "totalsize": "FIXME"}
                
            for x in getlist():
                for a in opts.get('architecture'):
                    pkgdir = os.path.join(x, arch_dir(a))
                    pkgs[pkgdir] = [ f for f in os.listdir(pkgdir) if os.path.isfile(os.path.join(pkgdir, f)) and ".deb" in f ]
                   
            print(json.dumps(dict(ipaddr=socket.gethostbyname(socket.gethostname()),
                                  filepath=os.path.abspath(path),
                                  apt=format_deb_line(socket.gethostbyname(socket.gethostname()),
                                                      opts.get('platforms'), opts.get('restrictions'), https=opts.get('https')),
                                  architectures=opts.get('architecture'),
                                  platforms=opts.get('platforms'),
                                  repositories={r: repo_dict(r, pkgs) for r in pkgs},
                                  contribs=opts.get('restrictions'),
                                  valid=repo_path_validate(path, opts.get('platforms'), opts.get('restrictions')),
                                  webserverroot=os.path.abspath(os.path.join(opts.get('directory'), opts.get('toplevel')))), 
                             default=str,
                             sort_keys=True,
                             indent=4,
                             separators=(',', ': ',)))
    
    elif action == "add":
        # Adds a component to an existing repo.
        packages = args.action[1:]
        modifiedrepos = []
        if packages:
            for p in packages:
                if len(p) > 4 and p[-4:] == ".deb":
                    for rpath in getlist():
                        # Seperate package from path
                        newp = p.split(os.sep)[-1]
                        for arch in opts.get('architecture'):
                            arch = get_arch(arch)
                            rpath = os.path.join(rpath, arch_dir(arch))
                            shutil.copyfile(p, os.path.join(rpath, newp)) # No metadata copied, need to chown and chmod?
                            if not rpath in modifiedrepos:
                                modifiedrepos.append(rpath)
                            print("Copying {} to {}".format(p, os.path.join(rpath, arch_dir(arch), newp)))
                            
        if modifiedrepos:
            for mr in modifiedrepos:
                print(os.path.join(opts.get('directory'), opts.get('toplevel')))
                Packages_gz(os.path.join(opts.get('directory'), opts.get('toplevel')), mr)
    
    elif action == "remove":
        modifiedrepos = []
        packages = args.action[1:]
        if packages:
            for rpath in getlist():
                for a in opts.get('architecture'):
                    modified = False
                    files = [ f for f in os.listdir(os.path.join(rpath, arch_dir(a))) if f[-4:] == ".deb" ]
                    for f in files:
                        # we compare the debian package name, omit the version and arch string which should be standard.
                        # We also check for verbatim comparisons
                        splt = f.split('-')
                        for foundpkg in filter(lambda x: '-'.join(splt[0:len(splt)-1]) == x, packages):
                            os.remove(os.path.join(rpath, arch_dir(a), f))
                            modified = True
                            print("Found {}, Removing {} from {}".format(foundpkg, f, os.path.join(rpath, arch_dir(a))))
                            
                        for foundpkg in filter(lambda x: x == f, packages):
                            os.remove(os.path.join(rpath, arch_dir(a), f))
                            modified = True
                            print("Removing {}".format(os.path.join(rpath, arch_dir(a), foundpkg)))
                            
                    if modified:
                        modifiedrepos.append(rpath)
                            
        if modifiedrepos:
            for mr in modifiedrepos:
                Packages_gz(os.path.join(opts.get('directory'), opts.get('toplevel')), mr)
        
    elif action == "haspkg":
        # Initialize search results
        # NOTE: This complex code can be eliminated with the introduction of a database
        pkgs = {}
        pkglist = []
        for x in getlist():
            for a in opts.get('architecture'):
                pkgdir = os.path.join(x, arch_dir(a))
                pkgs[pkgdir] = []
                pkglist = [ f for f in os.listdir(pkgdir) if os.path.isfile(os.path.join(pkgdir, f)) and ".deb" in f ]
                for pkg in args.action[1:]:
                    for p in pkglist:
                        pkg = pkg.replace('.deb', '')
                        # Add package if the string is found in the name and if it isn't already added
                        if pkg in p:
                            if not p in pkgs[pkgdir]:
                                pkgs[pkgdir].append(p)
                
        print(json.dumps(pkgs, default=str, sort_keys=True,
                             indent=4, separators=(',', ': ',)))
    
    elif action == "export":
        for p in opts.get('platforms'):
            print(format_deb_line(socket.gethostbyname(socket.gethostname()),
                                  [p], opts.get('restrictions'), https=opts.get('https')))
            
        # TODO: Source repository names
        
    elif action == "gpg":
        # Here we might want to automatically create some work (fibinocchi sequence?)
        # while generating the key.
        # This generates the key how Debian would prefer it to be generated
        #gen_gpg_key()
        print("FIXME: gpg generation")
        
    elif action == "help":
        print()
        print("apt-repo program help")
        print("=====================")
        print()
        print("apt-repo is a repository-focused script that allows automation of admin tasks.")
        print("The following are actions that can be performed:")
        print()
        print("create: Creates the repository directory structure and all the necessary files")
        print("        in it to enable the user to connect to, and subsequently update from,")
        print("        an empty repository.")
        print()
        print("        Relevant Options:")
        print("        \to --directory (Specify where to create repository structure")
        print("        \to --desc (Set the Release file description")
        print("        \to --name (Sets the Release account name of the repository)")
        print("        \to --email (Sets the Release email account, usually maintainers'")
        print("        \to --architecture (Create directories for the specified ")
        print("                            architectures")
        print("        \to --toplevel (Top level directory is the suffix to the deb")
        print("                        sources.list")
        print("        \t              line, defaults to 'debian')")
        print("        \to --platforms (Create directories that separate packages")
        print("                         based on stability)")
        print("        \to --restriction (Create directories for free/non-free/")
        print("                           contrib packages.")
        print()
        print("delete: Removes the repository directory structure completely")
        print("        Relevant Options:")
        print()
        print("        \to --directory (Specify where repository is to remove)")
        print()
        print("update: Adds or removes certain components to the repository, such as")
        print("        architectures, platforms, and package restrictions (non-free)")
        print()
        print("        \to --architecure")
        print("        \to --platforms")
        print("        \to --restrictions")
        print("        \to --name")
        print("        \to --email")
        print("        \to --desc")
        print("        \to --directory")
        print("        \to --toplevel")
        print()
        print("gpg:    Generates the gpg key. For now, let's assume the user can ")
        print("        create their own, as entropy and environment are important")
        print("        for the creation of a good key.")
        print()
        print("info:   ")
        print()
        print("add:   ")
        print()
        print("remove:   ")
        print()
        print("haspkg:   ")
        print()
        
    elif action is None:
        sys.stderr.write("Error: An ACTION was required, but not found.\n")
        sys.exit(3)
            
    
    # <-- Action has been performed, if successful we exit with 0 status
    """
    
    sys.exit(0)